/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Struct, StructInterface } from "../../struct.sol/Struct";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ikun",
    outputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "int256",
        name: "num",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5060408051808201909152600481526334b5bab760e11b60208201525f9061003790826100da565b506004600155610199565b634e487b7160e01b5f52604160045260245ffd5b600181811c9082168061006a57607f821691505b60208210810361008857634e487b7160e01b5f52602260045260245ffd5b50919050565b601f8211156100d557805f5260205f20601f840160051c810160208510156100b35750805b601f840160051c820191505b818110156100d2575f81556001016100bf565b50505b505050565b81516001600160401b038111156100f3576100f3610042565b610107816101018454610056565b8461008e565b602080601f83116001811461013a575f84156101235750858301515b5f19600386901b1c1916600185901b178555610191565b5f85815260208120601f198616915b8281101561016857888601518255948401946001909101908401610149565b508582101561018557878501515f19600388901b60f8161c191681555b505060018460011b0185555b505050505050565b6101ba806101a65f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c80639d65f8f01461002d575b5f80fd5b61003561004c565b6040516100439291906100e1565b60405180910390f35b5f8054819061005a90610133565b80601f016020809104026020016040519081016040528092919081815260200182805461008690610133565b80156100d15780601f106100a8576101008083540402835291602001916100d1565b820191905f5260205f20905b8154815290600101906020018083116100b457829003601f168201915b5050505050908060010154905082565b604081525f83518060408401525f5b8181101561010d57602081870181015160608684010152016100f0565b505f606082850101526060601f19601f8301168401019150508260208301529392505050565b600181811c9082168061014757607f821691505b60208210810361017e577f4e487b71000000000000000000000000000000000000000000000000000000005f52602260045260245ffd5b5091905056fea2646970667358221220e05ece10c028310adbc2426ca4b66ede61323358315e9c3463f6a9a511c5af0564736f6c63430008180033";

type StructConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StructConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Struct__factory extends ContractFactory {
  constructor(...args: StructConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Struct & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Struct__factory {
    return super.connect(runner) as Struct__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StructInterface {
    return new Interface(_abi) as StructInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Struct {
    return new Contract(address, _abi, runner) as unknown as Struct;
  }
}
