/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as structSol from "./struct.sol";
export type { structSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { Struct } from "./struct.sol/Struct";
export { Struct__factory } from "./factories/struct.sol/Struct__factory";
